service:
  name: host-listing-service

plugins:
  - serverless-offline
  - serverless-bundle

package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
